apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaaplication
  labels:
    app: javaaplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaaplication
  template:
    metadata:
      labels:
        app: javaaplication
    spec:
      containers:
      - name: javaaplication
        image: krishna2710/javaaplication:replaceImageTag
        ports:
        - containerPort: 8080
